-- Seed team members from Airtable CSV export
-- This migration inserts team member data into the team_members table
-- Note: Image URLs are extracted from Airtable attachment format

INSERT INTO public.team_members (name, position, bio, image_url, priority)
VALUES
  ('Scott Murff', 'Faculty Advisor', 'Scott is a Professor of Strategy at BYU. With experience at McKinsey & Company he is passionate about helping students develop their product management skills and is excited to be a part of the PM Association.', 'https://v5.airtableusercontent.com/v3/u/50/50/1771610400000/KTUnf7fvGlHWGoMKDp7lBA/ml1_WDdgWa_1qJBNGshai6zGf1Py1fuD4wQMe6JcU4pSE4_VHDy-NINFX0FonkXL4JGSGnddqpk_sp1h_dE21ERgCnhwbM7y75prc40ZtPF4_kZS8xU9GtXxkkXM9tOm1IKp8wiBOiStRpzPBJM2SQYTFncH6kt7iimbDp9N69E/kE2i3z1e1rr2X6MHRCSD6BuwU_doPB8Qkukngb_M890', 1),
  ('Ella Moore', 'Co-President', 'Ella is a Strategic Management major from the Bay Area currently working at Indigo Institute an edtech startup. She is passionate about the intersection of people and products and is currently the Vice President of Events for the Women in Strategy Association. Ella excels at increasing organizational efficiency and planning impactful events that foster collaboration and community.', 'https://v5.airtableusercontent.com/v3/u/50/50/1771610400000/nF7VSppIihJq8q2wHXrCMQ/VX9G0Y4jGBrqBHOfno8gtCCkPuVp49e3T5mlZ0B0uXSqpvuGZHc9lTeVTntZBAQqVd7K-SmadCGuOLsN5NjX0_ONtwFbAETrtFcBuTsdhMHDzGhFbgFv4LTmymzHZtzG6E1t2joW-K074Mdx5ket_Q/N1HU4E8E9Ba7PW459_HBp5gbS2uCFFQM6yLWkmtJg94', 2),
  ('Dylan Mattern', 'Co-President', 'Dylan is an Information Systems major from Northern California. He is passionate about building products that bring value and collaborating with diverse teams. With experience in startups as well as big tech at Microsoft he is excited to share and work with fellow students.', 'https://v5.airtableusercontent.com/v3/u/50/50/1771610400000/kZk-meclw1qDWQOpvo3tRQ/Nc-zLwfOsb03NMUNSeTyqrYlxlz6OPU-SesSksD_craKCW8IjUaFxLvGTyEYfnyYcqrvcdqGgsJO1tIiDT7xXJRJXz323uJ6NiiWHCer3Q3oI0hf_YDP2pPo7a2yP7v6sn4QcwU9yVRLhBIk9kuqrKBAhwWmASSK5PLJyBYln9o/4JfwMl3tCE_Sy-3v0zw38oI6x5uoO7N9iM5WOSEv6Eg', 3),
  ('Nate McCauley', 'VP of Placement', 'Nate is a San Francisco native majoring in Strategic Management with a minor in Computer Science. He has PM experience at Instructure (Canvas LMS) and a background in private equity software investing. Nate is dedicated to empowering learners with AI and enjoys "Vibe Coding" AI SaaS products on the weekends.', 'https://v5.airtableusercontent.com/v3/u/50/50/1771610400000/Cmlnuq3dRA4UVBFUTU07ig/UFG0yu2_XS4X2FR9Z6xymPOAPHZg-rgvO3ab_CC3Kj2wBVIPDUCkz_SJhoDmebslIPHnnH1T5YOzCIzJwABItaGfM67lfsuTwT9uCpy-lC4XektGAzbxY0iRlqZjU45JqGnqO_9YMIZAamBHnXk5ww/0oN8SpK0s6zfNJo8hKQam8BblUpdkrFlz-yaEZ6qYYM', 4),
  ('Carter Field', 'VP of Growth', 'Carter from Highlands Ranch Colorado is a Strategic Management major and current product manager intern at Awardco. He''s completed the PM tract in the strategy program and is passionate about building great products with big impact. Outside of work Carter enjoys sports and loves the Denver Nuggets.', 'https://v5.airtableusercontent.com/v3/u/50/50/1771610400000/_zCQVQk5iJZYW_hKRu90Vg/eVc4bjTPPt6ABGhZog8VJyLTfAqbhhVWpm7fmm7iNgJU0Ult0phjObjO06TGbCzojuhBk2oPgWhgHYtKqoHi2sEIRFiE7Wyh7qYz0wU-rMFC0mJR1JFgMpndZGy0wu6pyiZlewR55ou2KRdQ44Esqse06AMq--fae1ppkpD27kw/EisdLDSdXkpaDRVnH6UDhaTRpDzpHebAWM-3DYKpE8U', 5),
  ('Mick Buck', 'VP of Events', 'Mick is a Finance major and Computer Science minor from Texas, currently bridging the gap between finance and technology as a Fintech Product Manager at Pattern. In addition to his industry work, he serves as a Research Assistant for the AI Human-Computer Interaction Lab at BYU. When he isn''t refining product roadmaps, Mick is usually checking off bucket list items like paragliding or catching a baseball game. He is passionate about building the PMA community and looks forward to helping members navigate the path to successful careers in Product Management!', 'https://v5.airtableusercontent.com/v3/u/50/50/1771610400000/Pa2KxU-BBomVd-sQWJ9DzQ/N10nq0305dsUFS-3doxbVm3gMJWQumKjjYSj7S6dyXanCwsoTZ1XEQHbtzMElEIr0aaZd1kCa_7zKphzqSdbV0IvwIXzLOoUo144yzMtwsfEMNrUgILRCSwbd1jiI5xZFeojBWRzo5lltmCgl07ggA9LCQnJlI7UsXUrzlu1R7k/49__tYLF-eoqui3zok7VJV-uUCQnnbCscDXiQwXGn38', 6),
  ('Justin Maxwell', 'VP of Technology', 'Justin is an Information Systems major who enjoys winter cold plunges. He excels at organizational effectiveness and visionary execution and loves Product Management!', 'https://v5.airtableusercontent.com/v3/u/50/50/1771610400000/gMeVbwNuUNFpDJWVbuWo3Q/UucXxqpZhm6yrI1owscq5qBdkKBr473XT-zvDCqlrAA6y8Wb93sTXYwY_1DDNdfAgzPfXQrqfE7ov9eHV4T2qSN5l0SilAsJV1MtEV6UqdFNnRzRzV0o3rNs87FNn8RC1HzID8JuvEhYWvhmOlH2k_R3PcDJx_iFXj2qHDqLwgY/tswICF4d5DdxNyP50uifQ4okeM490CehxrR66FchcUw', 7)
ON CONFLICT DO NOTHING;
